version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.17  # Use a Node.js image for running npm commands
    steps:
      - checkout  # Check out the code from the repository
      
      - run:
          name: Install npm packages
          command: npm install
        